Azure/Avere

- src/vfxt/azuredeploy-auto.json
Hi Anthony,
Another PR, now to expose the vnet address space and subnet address range so deployment gets a little bit more flexible. I'm going to use this template extensively since I'm working on a whitepaper with vFXT in it.
Regards
Paulo
> Exposing vnet address space and subnet address range as parameters

- src/go/pkg/edasim/batch.go
use a hash code to avoid collisions and keep a small path name
> use a hash code for the job

- azure-pipelines.yml
- test/arm_template_deploy.py
- test/conftest.py
- test/lib/helpers.py
- test/test_edasim.py
- test/test_vdbench.py
- test/test_vfxt_cluster_status.py
- test/test_vfxt_template_deploy.py
Added custom command-line args to these tests so we can specify overrides on the command line more easily. More to come, but this is the first pass.
Example invocation:
`pytest test/test_vfxt_template_deploy.py --ssh_priv_key ~/.ssh/id_rsa_pipelines --ssh_pub_key ~/.ssh/id_rsa_pipelines.pub --test_vars_file TESTING.A.json --location northcentralus`
> Added command-line arguments to conftest.py

- src/vfxt/README.md
Since the deploy template links to this page, which can be confusing, I propose adding a note that links any lost template users back to the user-friendly roles documentation.
> add link to user doc

- azure-pipelines.yml
- test/conftest.py
- test/lib/helpers.py
- test/requirements.txt
- test/test_vfxt_cluster_status.py
Bare Paramiko calls can sometimes result in hung thread locks. Using Fabric calls instead (which use Paramiko under the hood) seems to reduce (or perhaps alleviate/eliminate) the frequency of those locks.
This is a first pass at transitioning Paramiko calls to Fabric. More updates coming.
> Convert Paramiko SSH calls to Fabric to alleviate some hung thread locks

- test/lib/helpers.py
**get_unused_local_port** (in helpers.py) identifies a free local port. However, the original version could, on occasion, return a port that wasn't actually available (race condition?). This change attempts to address it with a refactor and setting socket options.
> Fix get_unused_local_port

- azure-pipelines.yml
- test/conftest.py
- test/test_vfxt_cluster_status.py
- test/test_vfxt_template_deploy.py
When looking for a free network port, we actually connect to a system-chosen port first then disconnect from that port and return the port number. There seems to be an occasional race where the port isn't yet fully disconnected/available. This change attempts to address this by retrying the port connection five times (with a one-second sleep between tries).
Some other miscellaneous fixes are included:
- Added a new "common deploy error message" to the Pipelines YAML.
- Added timeouts to the commands in the mnt_nodes fixture (particularly for the mount command, which sometimes hangs).
- Renamed test_ping_nodes to test_ping_vservers.
- Fixed up some logger names in test_vfxt_template_deploy.py.
> Retry tunnel connection; other misc fixes

- azure-pipelines.yml
Log collection was using a pytest testcase, but when deployment fails, that collection testcase will also fail. So this change adds a second attempt at grabbing vfxt.log from the controller in the Pipeline (when vfxt.log isn't found).
> Collect vfxt.log even when deploy fails

- azure-pipelines.yml
If there is no vfxt.log for some reason when we get to the INFO step (version check), the step will hang since grep will be waiting for input.
> Fix hang when no vfxt.log during INFO version step

- test/conftest.py
The mount (cluster nodes onto controller) call occasionally hangs, and it's not clear why. This change adds more detailed output to help future investigations.
- lowered retry time for /etc/fstab entries to 5 minutes instead of 30
- added -v (verbose) flag to mount call
- output /etc/mtab when there's a mount failure to see what was currently mounted at the time
Hopefully the above gets us closer to a root cause and fix. This branch will remain open to eventually be the vehicle for checking in the fix.
> Lowered retry time for mounting nodes; added verbose flag

- test/internal/region_deploy_utils.py
We can use the Partition/Row key combo to uniquely track table control values in the Azure Table. So the "column" name can be consistent for these table control fields. Updating the "column" to be "VALUE." LogicApp also updated.
> /test: Simplifying table fields for region deploy tracking

- test/conftest.py
Repros show "route to host not found," not just for a particular vserver IP, but also for the management IP. That could mean a particular node is down, but could also indicate a network problem. Adding diag output for the latter first.
> More diag output when mount command hangs

- test/conftest.py
Looks like portmap restart didn't help, so removing that. Adding some more network diag for when mount hangs next time. It's action, reaction, random interaction.
> Remove portmap restart, add more network diag

- azure-pipelines.yml
- test/conftest.py
- test/test_vfxt_cluster_status.py
This is a larger iteration of attempting to diagnose/fix the hung mount command issue.
One of the issues we see when the mount command hangs is that subsequent XML RPCs to the cluster fail. Assuming a node went down (and thus the hung mount), the XML RPCs could be failing because they are attempting to hit a cluster management IP that may be migrating. As a result, we can't collect node logs, check for cores, etc.
This change attempts to alleviate this situation by trying averecmd calls against various cluster IPs. It doesn't fix the hung mount issue, but should (hopefully) help us collect more information in tracking that down.
Also, a new test case appears (test_ping_node_ips)! And some other test case re-ordering and cleanup.
> Added resiliency for averecmd to collect logs, etc

- azure-pipelines.yml
Added a step to the Pipeline that checks collected artifacts for certain error messages. If any of these messages are found, then this new step will fail and therefore the Pipeline run overall will be considered a failure.
Presently, this is implemented as a fairly straightforward recursive grep (using Perl-style regex). As we find more use cases (or special cases), we should consider writing/using a tool with more intelligent logic.
> Added "check for err msgs" step to Pipeline

- test/internal/region_deploy_utils.py
Update the region rotation utility to ignore an additional two regions not supported in the test sub.
> Region updates

- src/vfxt/README.md
Update README's URL for the Azure Marketplace Wizard to https://portal.azure.com/?pub_source=email&pub_status=success#create/microsoft-avere.vfxt-templateavere-vfxt-arm
Prior URL was to the preview version.
PS: My editor got rid of some trailing spaces, too.
> Update Azure Marketplace Wizard URL

- CODEOWNERS
I'm not sure if this syntax is right (any way to test it?) - but my intent is to add myself and other doc-focused people as automatic reviewers for files within the public-facing documentation and legacy docs subsections. 
- Should the overall code owners also be notified/asked for reviews? 
- Should different people be involved than I used?
> add writers to codeowners for docs

- docs/vdbench.md
1) Updated to use full official product names in a few places and not in others (Azure HPC Cache is unfortunately not decomposable as a proper name)
2) Updated links to point to docs.microsoft.com versions; also added links to product pages for both 
3) HPC cache doesn't expose the concept of clusters & nodes so I updated the "per 3 nodes" to include the comparable sizing language
> Minor text cleanup

- test/internal/region_deploy_utils.py
Updating the region rotation scheduler to exclude the new Norway-based regions until we can get them added to the test subscription.
> Update region exclusion list (Norway regions)

- azure-pipelines.yml
The ping tests succeed intermittently, likely due to a race condition between cluster network stabilization and the test. Will investigate further, but disabling the ping tests for now since the other tests explicitly test cluster health.
> Disable ping tests (intermittent success)

- src/terraform/examples/vfxt/opencue/new-storage/cloud-init.yml
- src/terraform/examples/vfxt/opencue/new-storage/main.tf
- src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/cloud-init.yml
- src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/main.tf
To comply with subscription policies
- add ssh port to opencue terraform
- add ssh key to vfxt to comply with ssh key policy
Two additional updates:
1. namespace path passed through to cloud-init
2. added module dependency so the vmss module does not fire early
> add configurable ssh port and key to comply with subscription policies

- src/clientapps/opencue/README.md
- src/clientapps/opencue/bootstrap.sh
- src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/moanaislandscenescripts/renderAll.sh
Generalise opencue bootstrap.sh file for the RQD render nodes - build PBRT by default rather than copy
Add notes on what each expected environment variable is used for
Update sample render script to use the location of PBRT in the bootstrap.sh script and the default user in the terraform script as the output directory
> Opencue updates

- src/terraform/providers/terraform-provider-avere/averevfxt.go
- src/terraform/providers/terraform-provider-avere/go.sum
- src/terraform/providers/terraform-provider-avere/resource_vfxt.go
fixes #804 .  The set type does not correctly set the state for the computed values, so changing those to list types.
> ensure scale-up correctly outputs node names and ip addresses

- src/terraform/providers/terraform-provider-avere/README.md
- src/terraform/providers/terraform-provider-avere/averevfxt.go
- src/terraform/providers/terraform-provider-avere/constants.go
- src/terraform/providers/terraform-provider-avere/go.sum
- src/terraform/providers/terraform-provider-avere/resource_vfxt.go
- src/terraform/providers/terraform-provider-avere/types.go
fixes #794 
This is useful if you need to connect to multiple nodes, and you do not want the IPs to move while an AOS service is restarting.
> add static node ip addresses

- src/terraform/providers/terraform-provider-avere/README.md
- src/terraform/providers/terraform-provider-avere/averevfxt.go
- src/terraform/providers/terraform-provider-avere/constants.go
- src/terraform/providers/terraform-provider-avere/resource_vfxt.go
- src/terraform/providers/terraform-provider-avere/restore_backup.go
Fix for #762 
There was a misunderstanding in the configuration of the cache policy, it is not a high write back delay, but a high core filer verification time.
> Fix read only cache policy

- src/clientapps/vdbench/bootstrap.vdbench.sh
Fixed an issue that was limiting vdbench to no more than 15 loadgen clients. This update will allow support for up to 255 clients.
> left-padding of HOST_NUMBER_HEX to increase support from 15->255 vdbench loadgen clients

- src/terraform/modules/dnsserver/main.tf
- src/terraform/modules/dnsserver/variables.tf
used to emulate search domains or specify other names
fixes #955
> add alternate fqdns to dns server

- src/terraform/providers/terraform-provider-avere/averevfxt.go
- src/terraform/providers/terraform-provider-avere/resource_vfxt.go
also gsi debugging hit a known_hosts bug, so the PrepareForVFXTNodeCommands has to be run immediately after cluster creation
> add code from GSI debugging

- src/terraform/providers/terraform-provider-avere/resource_vfxt.go
If support uploads is not set, removal of corefiler will trigger a support upload.  A guard is needed to ensure the stats upload will only run if support uploads and active uploads is enabled.
> missing guard on upload

- src/terraform/modules/hammerspace/anvil-run-once-configure/main.tf
Fixes the following error when deploying:
│ Error: Invalid template interpolation value
│
│   on .terraform/modules/anvil_configure/src/terraform/modules/hammerspace/anvil-run-once-configure/main.tf line 5, in locals:
│    5:   command = "mkdir -p /opt && touch /opt/configure-anvil.py && echo ${local.script_file_b64} | base64 -d | gunzip > /opt/configure-anvil.py && python2 /opt/configure-anvil.py ${var.anvil_data_cluster_ip} ${var.web_ui_password} ${var.dsx_count}  -a '${var.ad_domain}' -u '${var.ad_user}' -p '${var.ad_user_password}' -n '${var.local_site_name}' -s '${var.nfs_export_path}' --azure-account '${var.azure_storage_account}' --azure-account-key '${var.azure_storage_account_key}' --azure-account-container '${var.azure_storage_account_container}' "
│     ├────────────────
│ …
> Fix error: var.web_ui_password is list of string with 1 element

- src/terraform/examples/hammerspace-multi-region/2.hammerspace/main.tf
- src/terraform/examples/hammerspace/main.tf
- src/terraform/examples/vfxt/hammerspace/main.tf
- src/terraform/modules/hammerspace/anvil-run-once-configure/main.tf
```
√ hammerspace $ terraform apply -auto-approve
╷
│ Error: Unsupported attribute
│
│   on main.tf line 195, in output "anvil_data_cluster_data0_ip":
│  195:   value = module.anvil.anvil_data_cluster_data0_ip
│     ├────────────────
│     │ module.anvil is a object, known only after apply
│
│ This object does not have an attribute named "anvil_data_cluster_data0_ip".
╵
╷
│ Error: Unsupported attribute
│
│   on main.tf line 199, in output "anvil_data_cluster_data1_ip":
│  199:   value = module.anvil.anvil_data_cluster_data1_ip
│     ├────────────────
│     │ module.anvil is a object, known only after apply
│
│ This object does not have an attribute named "anvil_data_cluster_data1_ip".
```
> Fix for Error: Unsupported attribute in Hammerspace example

- docs/previews/hpc-priming.html
- docs/previews/preview-features.html
Intent is to create a page that can hold basic user documentation for private preview feature documentation. For now the only page will be for the HPC Cache priming feature, but other products and features might use this space in the future. 
The page will be accessed directly by its URL, not linked from of any well-known existing page in this repository. This URL will be referenced by a redirect link that will be explicitly provided to preview participants and internal staff. When public preview begins, the material here will be moved to a first-level published docs.microsoft.com page.
I'm not sure if there's a risk of exposure by having the page here - it can be browsed to by anyone with access to the repository. It should not be indexed by search engines (is that still a thing?). 
For …
> Create web pages for feature preview documentation
