docs/azure_vm_provision_best_practices.md
=> Revert "fix document based on feedback"

src/clients/loosevms/azuredeploy.json, src/clients/vmas/azuredeploy.json, src/clients/vmss/azuredeploy.json, src/nfslatency/azuredisknfs/nfs-azuredeploy.json, src/storageaccount/azuredeploy.json, src/vfxt-auto/azuredeploy.json, src/vfxt-vnet/azuredeploy.json, src/vfxt/azuredeploy.json, src/win10vfxtmounted/parts/base-template.json, src/win10vfxtmounted/win10-azuredeploy.json
add usage guid per https://docs.microsoft.com/en-us/azure/marketplace/azure-partner-customer-usage-attribution
=> add usage guid 

src/vfxt/README.md, src/vfxt/azuredeploy-auto.json
Included some bug fixes in the document and I also included some extra information as well that will help our users to deploy using this template.
=> Bug fixes in the readme file and some extra information

src/vfxt/README.md, src/vfxt/azuredeploy-auto.json, src/vfxt/azuredeploy-auto.parameters.json, src/vfxt/azuredeploy.json, src/vfxt/azuredeploy.parameters.json, src/vfxt/oneshotgen/base-template.json, src/vfxt/oneshotgen/createUiDefinition.json, src/vfxt/recover_sp_information.md
Hi Anthony,
Just realized that I didn't add the parameters to the parameters file, including them now.
I also noticed that some parameter names contains "?" symbol and I removed it since although I looks good in the Portal deployment blade it may introduce challenges to someone trying to deploy it in an automated fashion, for example from a bash script.
Regards
Paulo
=> Adding new ip address related parameters and adjusting some names

src/vfxt/README.md, src/vfxt/recover_sp_information.md
Hi Anthony,
Fixed numbered list of steps and an important fix in the syntax of the recovery SP information steps.
Regards
Paulo
=> Fixed command typo and step numbers

src/go/cmd/blobuploader/main.go, src/go/cmd/randtester/main.go, src/go/pkg/edasim/jobconfigfile.go, src/go/pkg/edasim/workfilewriter.go, src/go/pkg/random/random_string.go
- add shorter dir name
- add faster rand string
=> speed up randomstring

azure-pipelines.yml, test/avere_template_deploy.py, test/requirements.txt, test/test_avere_template_deploy.py
Intended to facilitate easier test-writing using pytest.
=> Moving to OO model.

azure-pipelines.yml, test/avere_template_deploy.py, test/test_avere_template_deploy.py
Still need to add sub ID to the right key vault spaces.
vfxt.py still failing intermittently.
=> First pass at pytest with the test script

test/test_avere_template_deploy.py
Add in commands once on controller and mount.
Download template and deploy with correct params.
=> ssh commands/vdbench

src/vfxt/src/createUiDefinition.json
Updated template labels and help. Please check that I made things better & didn't break anything.
=> Tweak labels & tooltips on template

azure-pipelines.yml
Added the **skip_rg_cleanup** variable so we can skip cleanup on a re-queue. Plus other miscellaneous minor updates.
=> Pipelines YAML updates

azure-pipelines.yml
Simple grep vfxt.log for " version" to see vfxt.py and AvereOS versions.
Also displays region used during deployment.
=> Add version, region info step to YAML

azure-pipelines.yml, src/vfxt/azuredeploy.vnet.json, test/conftest.py, test/lib/helpers.py, test/test_vfxt_cluster_status.py
- Add azuredeploy.vnet.json back in src/vfxt
=> Fix vnet test

test/conftest.py
Another update after a weekend where the mount issue cropped up a couple of times. It looks like we can't get to the last node's vserver IP. Hedging on the client side, so this update adds a portmap restart prior to the mount command (with a short sleep between commands, just in case).
=> Restart portmapper before mounting

src/vfxt/src/enablecloudtrace.sh
Change to collect trace needed for more debugging after deployment
=> Enable trace

azure-pipelines.yml
Add better error reporting for some of the pytest steps to more easily identify failures.
=> Add better error reporting

test/internal/region_deploy_utils.py, test/test_vdbench.py, test/test_vfxt_template_deploy.py
* Template name hardening.
* Quote vdbench download URL.
* Exclude new Switzerland regions from multi-region testing (for now).
=> Test updates

docs/legacy/ops_guide/4_7/html/gui_ha.html, docs/legacy/ops_guide/4_7/html/gui_manage_cache_policies.html
Added notes to two pages because UI has changed slightly. Edited HTML only.
=> Legacy doc - minor updates to 4.7 ops guide

src/terraform/providers/terraform-provider-avere/averevfxt.go, src/terraform/providers/terraform-provider-avere/resource_vfxt.go, src/terraform/providers/terraform-provider-avere/ssh.go
- add list exports when add junction fails to poke the vfxt
- add ensure stability after creating core filer or junction
- do not block on yellow errors
=> avere vfxt rpc improvements

azure-pipelines.yml
Disable PublishPipelinesArtifact task.
=> Disable PublishPipelinesArtifact task

src/terraform/providers/terraform-provider-avere/resource_vfxt.go
There is a ordering bug where the DNS is set after adding the core filers and the corefilers cannot be set be set. This PR sets the correct ordering.
=>  create formal ordering for create and update paths

test/test_vfxt_cluster_status.py
Add a new testcase to collect GSIs during scheduled pipelines runs.
=> Add new testcase (test_collect_gsi)

src/clientapps/opencue/README.md, src/clientapps/opencue/bootstrap.sh, src/terraform/modules/opencue_config/README.md, src/terraform/modules/opencue_config/main.tf, src/terraform/modules/opencue_config/outputs.tf, src/terraform/modules/opencue_config/variables.tf, src/terraform/modules/vmss_mountable/main.tf, src/terraform/modules/vmss_mountable/variables.tf
First pass at opencue modules needed for the deployment. 
bootstrap script not complete, but need a version live for testing.
Added a new variable to VMSS module to allow passing in additional environment vars needed for OpenCue
=> Adding OpenCue config modules

src/terraform/examples/vfxt/1-filer/main.tf, src/terraform/examples/vfxt/3-filers/main.tf, src/terraform/examples/vfxt/HoudiniOptimized/main.tf, src/terraform/examples/vfxt/azureblobfiler/main.tf, src/terraform/examples/vfxt/cachewarmer/1.networkandfiler/main.tf, src/terraform/examples/vfxt/cachewarmer/2.vfxtcontroller/main.tf, src/terraform/examples/vfxt/cachewarmer/3.vfxtandcachewarmer/main.tf, src/terraform/examples/vfxt/cloudworkstation/collaboratingcloudworkstation/main.tf, src/terraform/examples/vfxt/cloudworkstation/isolatedcloudworkstation/main.tf, src/terraform/examples/vfxt/custom-vserver/main.tf, src/terraform/examples/vfxt/netapp-across-region/main.tf, src/terraform/examples/vfxt/netapp/main.tf, src/terraform/examples/vfxt/no-filers/main.tf, src/terraform/examples/vfxt/proxy/main.tf, src/terraform/examples/vfxt/run-local/main.tf, src/terraform/examples/vfxt/test-cluster/main.tf, src/terraform/examples/vfxt/vdbench/azureblobfiler/main.tf, src/terraform/examples/vfxt/vdbench/nfsfiler/main.tf, src/terraform/examples/vfxt/vfxt-only/main.tf, src/terraform/examples/vfxt/vfxt-only/simulated_environment/main.tf, src/terraform/examples/vfxt/vmss/main.tf, src/terraform/examples/vmss-rendering/azuredeploy.json, src/terraform/examples/vmss-rendering/main.tf, src/terraform/modules/jumpbox/main.tf, src/terraform/modules/nfs_filer/main.tf, src/terraform/modules/nfs_filer_legacy/main.tf, src/terraform/modules/proxy/main.tf
purpose is to align with Azure policies:
* close port 22, 3389
* ssh key on all linux variants
=> update examples with tcp port and ssh for vfxt

src/clientapps/opencue/bootstrap.sh, src/terraform/modules/opencue_config/main.tf
Update opencueconfig module to use the bootstrap script on dev branch. Enable testing without needing to merge to master
=> Opencue terraform deployment

src/terraform/examples/vfxt/opencue/new-storage/README.md, src/terraform/examples/vfxt/opencue/new-storage/cloud-init.yml, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/README.md, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/cloud-init.yml, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/main.tf, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/moanaislandscenescripts/island.pbrt, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/moanaislandscenescripts/islandX.pbrt, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/moanaislandscenescripts/island_4096.pbrt, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/moanaislandscenescripts/island_beachCam.pbrt, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/moanaislandscenescripts/island_dunesACam.pbrt, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/moanaislandscenescripts/island_frame90.pbrt, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/moanaislandscenescripts/island_grassCam.pbrt, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/moanaislandscenescripts/island_hibiscusCam.pbrt, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/moanaislandscenescripts/island_palmsCam.pbrt, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/moanaislandscenescripts/island_rootsCam.pbrt, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/moanaislandscenescripts/island_shotCam.pbrt, src/terraform/examples/vfxt/opencue/pre-existing-azure-blob/moanaislandscenescripts/renderAll.sh
Fix bug: OpenCue pre-pop storage terraform VMSS depends duplication
Add to the docs details on setting up VNC, and how to start CueGui and CueSubmit
Include sample scripts to execute moana island scene jobs
Improve logging in cloud-init file
add re-tries to wget in cloud-init
Bump terraform provider link to 0.9.2 version, needed for ssh_port configuration option.
=> bug fix, improve docs, and add sample scripts

src/terraform/providers/terraform-provider-avere/resource_vfxt.go
=> add read of password, accidently removed in #770

src/terraform/providers/terraform-provider-avere/README.md, src/terraform/providers/terraform-provider-avere/averevfxt.go, src/terraform/providers/terraform-provider-avere/constants.go, src/terraform/providers/terraform-provider-avere/resource_vfxt.go, src/terraform/providers/terraform-provider-avere/restore_backup.go
=> Issue 762 read only cache policy

src/terraform/providers/terraform-provider-avere/constants.go, src/terraform/providers/terraform-provider-avere/resource_vfxt.go, src/terraform/providers/terraform-provider-avere/types.go
=> add check for vfxt name and licensing id output

src/terraform/providers/terraform-provider-avere/README.md, src/terraform/providers/terraform-provider-avere/averevfxt.go, src/terraform/providers/terraform-provider-avere/constants.go, src/terraform/providers/terraform-provider-avere/resource_vfxt.go, src/terraform/providers/terraform-provider-avere/types.go
=> ensure deterministic core filer ordering

src/terraform/providers/terraform-provider-avere/README.md, src/terraform/providers/terraform-provider-avere/averevfxt.go, src/terraform/providers/terraform-provider-avere/constants.go, src/terraform/providers/terraform-provider-avere/resource_vfxt.go, src/terraform/providers/terraform-provider-avere/types.go
=> add mechanism to divide up cache

src/terraform/providers/terraform-provider-avere/averevfxt.go, src/terraform/providers/terraform-provider-avere/constants.go, src/terraform/providers/terraform-provider-avere/resource_vfxt.go, src/terraform/providers/terraform-provider-avere/types.go
=> wait for balancing to complete before halting balancing

src/terraform/providers/terraform-provider-avere/averevfxt.go, src/terraform/providers/terraform-provider-avere/command.go, src/terraform/providers/terraform-provider-avere/types.go
=> ensure corefiler can take multiple addresses

src/terraform/providers/terraform-provider-avere/constants.go, src/terraform/providers/terraform-provider-avere/resource_vfxt.go
=> update balancing algorithm

src/terraform/providers/terraform-provider-avere/averevfxt.go
=> add the enable api, and core filer deletion as a multi-api call

src/terraform/providers/terraform-provider-avere/averevfxt.go
=> enable the analytics api so it doesn't get permission denied

src/terraform/providers/terraform-provider-avere/custom_settings.go
=> deprecate custom settings

src/terraform/README.md, src/terraform/examples/vfxt/README.md, src/terraform/examples/vfxt/user-assigned-managed-identity/README.md, src/terraform/modules/controller/msazure.py.patchidentity
1. link example from main readme, and vfxt examples readme files
1. ensure all role assignment code is protected with a retry in case there are AAD propagation errors
1. update vfxt.py patch to match latest vfxt.py changes related to identity
=> update docs and vfxt.py code for user assigned managed identity

src/terraform/examples/houdinienvironment/Get-AvereFlatFiles.ps1
update script to only include users in group files and with their SamAccountName
=> update AD flat file group file

docs/index.html, docs/legacy/supported-ciphers.html
Because MD only looks good in my editor....
=> Change ciphers doc from md to html

src/terraform/providers/terraform-provider-avere/resource_vfxt.go
=> improve ssh key validation

src/terraform/modules/controller/msazure.py.patchidentity, src/terraform/providers/terraform-provider-avere/averevfxt.go
fixes #892 (fixed by commenting out two lines in the vfxt.py patch)
=> fix scale-up / scale-down errors

src/terraform/providers/terraform-provider-avere/averevfxt.go, src/terraform/providers/terraform-provider-avere/resource_vfxt.go
=> fix unnecessary core filer removals

src/terraform/providers/terraform-provider-avere/averevfxt.go, src/terraform/providers/terraform-provider-avere/cifs.go, src/terraform/providers/terraform-provider-avere/resource_vfxt.go
=> add ability to empty the SMB share aces

src/terraform/providers/terraform-provider-avere/README.md, src/terraform/providers/terraform-provider-avere/averevfxt.go, src/terraform/providers/terraform-provider-avere/cifs.go, src/terraform/providers/terraform-provider-avere/constants.go, src/terraform/providers/terraform-provider-avere/junction.go, src/terraform/providers/terraform-provider-avere/resource_vfxt.go, src/terraform/providers/terraform-provider-avere/types.go
=> add cifs create and dir masks

src/terraform/examples/vfxt/cloudworkstation/README.md
Remove "experimental"
Change CIFS to SMB
Edit the info about installing Terraform if not using Cloud Shell
Add information about Clients Bypassing the Cluster and possible file collisions
=> Update cloud workstation readme

src/terraform/providers/terraform-provider-avere/averevfxt.go
=> fix domain rules so they can each be deployed independently

src/terraform/providers/terraform-provider-avere/README.md, src/terraform/providers/terraform-provider-avere/cifs.go, src/terraform/providers/terraform-provider-avere/resource_vfxt.go
=> fix validation bugs

src/terraform/modules/controller/main.tf, src/terraform/modules/controller/outputs.tf, src/terraform/modules/controller/variables.tf, src/terraform/modules/controller3/main.tf, src/terraform/modules/controller3/outputs.tf, src/terraform/modules/controller3/variables.tf
=> add option to deploy the controller

src/terraform/modules/controller3/cloud-init.tpl, src/terraform/modules/controller3/main.tf, src/terraform/modules/controller3/msazure.py.patchidentity
=> fix managed identity on the python 3 controller

src/terraform/providers/terraform-provider-avere/cifs_rid.go, src/terraform/providers/terraform-provider-avere/static/generate-rid-avereflatfiles.py
=> fix hardcoded domain in the rid mapping python

src/terraform/providers/terraform-provider-avere/averevfxt.go, src/terraform/providers/terraform-provider-avere/constants.go
=> ensure gsi is uploaded before deleting cluster

src/terraform/providers/terraform-provider-avere/README.md, src/terraform/providers/terraform-provider-avere/averevfxt.go, src/terraform/providers/terraform-provider-avere/constants.go, src/terraform/providers/terraform-provider-avere/filer.go, src/terraform/providers/terraform-provider-avere/resource_vfxt.go, src/terraform/providers/terraform-provider-avere/restore_backup.go, src/terraform/providers/terraform-provider-avere/types.go
=> add filer class to core filer

src/terraform/modules/dnsserver/main.tf, src/terraform/modules/dnsserver/unbound.conf, src/terraform/modules/dnsserver/variables.tf
=> add tll variable to dns server

src/terraform/providers/terraform-provider-avere/averevfxt.go, src/terraform/providers/terraform-provider-avere/azure.go, src/terraform/providers/terraform-provider-avere/network.go
=> health check to ensure vserver ip addresses

src/terraform/providers/terraform-provider-avere/cifs_rid.go, src/terraform/providers/terraform-provider-avere/static/generate-rid-avereflatfiles.py
=> add paging to ldap queries for rid auto generation

src/terraform/providers/terraform-provider-avere/averevfxt.go
=> harden scale-up path

src/terraform/providers/terraform-provider-avere/averevfxt.go, src/terraform/providers/terraform-provider-avere/network.go
- sorting IP addresses was incorrect
- verification of vserver was incorrect for non-contiguous ranges
- there was no guard for a cifs update command
=> various bug fixes from code inspection

src/terraform/providers/terraform-provider-avere/cifs_rid.go, src/terraform/providers/terraform-provider-avere/static/generate-rid-avereflatfiles.py
=> rid generator to work with python3

src/terraform/providers/terraform-provider-avere/README.md, src/terraform/providers/terraform-provider-avere/averevfxt.go, src/terraform/providers/terraform-provider-avere/constants.go, src/terraform/providers/terraform-provider-avere/resource_vfxt.go
=> add capability to add a different checkattrperiod to client bypass policy

templates/rg_delete.yml
Terraform Pipeline: Add sub_id back in for RG delete.
=> Terraform Pipeline: Add sub_id in for RG delete

terraform.yml
Add more regions, will be updating logic app to use westeurope as main region for now.
=> Add regions

templates/terraform_setup.yml, terraform.yml
Adds preview-image support to Terraform testing pipeline.
=> (internal) add preview support to tests

src/terraform/examples/centos/stockimage/main.tf, src/terraform/examples/vmss-rendering/azuredeploy.json, src/terraform/examples/vmss-rendering/main.tf, src/terraform/modules/cyclecloud/main.tf, src/terraform/modules/dnsserver/main.tf, src/terraform/modules/hammerspace/anvil-run-once-configure/main.tf, src/terraform/modules/hammerspace/dsx/main.tf, src/terraform/modules/jumpbox/main.tf, src/terraform/modules/nfs_filer/main.tf, src/terraform/modules/nfs_filer_md/main.tf, src/terraform/modules/proxy/main.tf
=> update offer and sku of CentOS

src/terraform/providers/terraform-provider-avere/azure.go
=> add HTTP_PROXY env var

src/terraform/providers/terraform-provider-avere/averevfxt.go
=> avoid deleting default export rules

src/terraform/providers/docker/Dockerfile
Setting up dockerfile to build latest terraform provider and install Azure CLI.
=> Update dockerfile to full environment

azure-pipelines.yml
Rework the ARM template pipeline, simplifying the logic and using the BYOVnet model by default.
=> Internal: rework ARM template pipeline

src/terraform/examples/vfxt/1-filer/main.tf, src/terraform/examples/vfxt/3-filers/main.tf, src/terraform/examples/vfxt/HoudiniOptimized/main.tf, src/terraform/examples/vfxt/azureblobfiler-zonal/main.tf, src/terraform/examples/vfxt/netapp-across-region/main.tf, src/terraform/examples/vfxt/netapp/main.tf, src/terraform/examples/vfxt/no-filers/main.tf, src/terraform/examples/vfxt/proxy/main.tf, src/terraform/examples/vfxt/user-assigned-managed-identity/main.tf, src/terraform/modules/render_network_secure/main.tf, src/terraform/modules/render_network_secure/variables.tf
Add peer_vnet_rg and peer_vnet_name  set to empty string to other vfxt examples similar to azureblobfiler change.
=> add peer_vnet_rg and peer_vnet_name to other vfxt examples

templates/terraform_setup.yml, terraform.yml
Add sleep to start RunCommandLinux Failure on VMs.
Add retry logic.
=> Add sleep to start RunCommandLinux Failure on VMs

templates/cloud_init/cloud_init.client.yml, templates/terraform_setup.yml, templates/upload_gsi.yml, terraform.yml
Add gsi collection to terraform pipeline.
Custom URL to redirect where gsi lands internally.
=> Add gsi to terraform pipeline
